### ISSUE TITLE
vhosts should be symlinked to sites-available

### ISSUE THREAD

**Issue by CafeLungo** [geerlingguy/ansible-role-nginx#101]
This is just a minor thing, but to follow convention with debian (or at least ubuntu, I think), the vhost configs usually go in `/etc/nginx/sites-available/`, and then get symlinked from in `/etc/nginx/sites-enabled/`

**Comment by eRadical** [comment]
I just want to thumbs up @ilanco and mention he did a very good when he added this behavior only for debian/ubuntu...
On RHEL/CentOS/Fedora this should not happen [when I was in Puppet land the debian/ubuntu convention was forced upon us, I would hate it if it would be forced w/ Ansible also].

I also think that debian/ubuntu should consider discarding this convention as this is an (almost) ancient behavior (when we had more vhosts on a server)... nowadays it's usually the other way around (a vhost is on many servers)... but that's really a different discussion...

**Comment by CafeLungo** [comment]
I support either of these PRs. But not both. 😄

**Comment by eRadical** [comment]
I vote for @ilanco's fix!

Please mark this as not stale!

**Comment by simonspa** [comment]
This is still relevant.

**Comment by hummal** [comment]
bump up
