### ISSUE TITLE
Add support for Drupal private files

### ISSUE THREAD

**Issue by yobottehg** [geerlingguy/ansible-role-nginx#104]
At the moment DrupalVM is unable to serve private files in Drupal 8 due to a missing rule in nginx:

    location ~ ^(/[a-z\-]+)?/system/files/ {
        try_files $uri /index.php?$query_string;
    }

Perhaps this could be added.

**Comment by geerlingguy** [comment]
@yobottehg - Thanks for posting the issue! I actually haven't set up a D8 site with private files on Nginx yet, so I'm glad someone else has, and found this out. I don't think I'd add Drupal-specific modifications in this role though; are you using Drupal VM, or some other project? If not using Drupal VM, then the best way to add the modification would be to extend the base template to add that rule (or use your own template).

See: https://github.com/geerlingguy/ansible-role-nginx#overriding-configuration-templates

**Comment by yobottehg** [comment]
@geerlinguy I'm using DrupalVM and just had a look at the config that gets build on the server to recognise that this particular config was missing.

I understand that you do not want to add this here, should I open up an issue at DrupalVM?

**Comment by geerlingguy** [comment]
@yobottehg yeah, that'd be best, thanks!
