### ISSUE TITLE
server_name_redirect results in invalid vhost configuration

### ISSUE THREAD

**Issue by pehlert** [geerlingguy/ansible-role-nginx#106]
Setting server_name_redirect results in the following invalid vhost configuration file for me:

```
$ cat /etc/nginx/sites-enabled/foobar.com.conf
    listen       80;
    server_name  www.foobar.com;
    return       301 $scheme://foobar.com$request_uri;
}

server {

    listen 80;

    server_name foobar.com;

    root /home/wordpress/web;

    index index.php index.html index.htm;




}
```

This is quite an obvious effect from the vhost.j2 template, but maybe I'm missing something?

**Comment by pinkeen** [comment]
I'm having the same issue. Also was thinking - am I missing something? 
But this seems like a mistake. Moreover a http -> https redirect would be nice to have too ;)

**Comment by geerlingguy** [comment]
Yeah... for a lot of my sites that use SSL, I have a redirect defined like:

```
server
{
    listen       80;
    server_name  {{ nginx_server_name_80 }};
    return       301 https://{{ nginx_canonical_host }}$request_uri;
}
```

**Comment by pehlert** [comment]
Many thanks for fixing this :) Looks great now!
