### ISSUE TITLE
Default vhost for nginx 1.12+ on Debian has moved

### ISSUE THREAD

**Issue by noplanman** [geerlingguy/ansible-role-nginx#114]
Not sure in which version of Nginx this changed, but the default vhost config is no longer in `sites-enabled`, but instead has been moved to `conf.d/default.conf`.

For this reason, it would be great if the `nginx_default_vhost_path` could be overridden, just like the `nginx_user` variable.

Since we're at it, might as well make all paths overridable, no? Or is there a reason to enforce the defaults? I've read online that some users prefer to organise their Nginx stuff differently, i.e. different `conf.d` path, not to use `sites-enabled` at all, etc.

I'd be happy to PR this small change :+1:

**Comment by geerlingguy** [comment]
For now, I'd like to keep it one path at a time. And I'm definitely okay with you adding a PR to add `nginx_default_vhost_path`—but I'd like to make sure it always works by default in any LTS-type OS install.

In which version of Debian did you see this happen? I haven't checked too closely with Debian 9/Stretch, but I do have a Docker container for testing with 9, and a Vagrant box for 9 as well.

**Comment by noplanman** [comment]
> I'd like to make sure it always works by default in any LTS-type OS install.

Absolutely! The only thing I'd be changing, is giving the user the option to be able to override it, default will stay the same, exactly as it is now.

Not sure if it's due to Debian or Nginx version, but on Stretch with Nginx 1.12 and up I see this. You'll need to add the Nginx source from here:
https://nginx.org/en/linux_packages.html#stable

**Comment by geerlingguy** [comment]
@noplanman - Is this something that changed in Debian 9 or 10? I haven't had an issue in my own testing but admittedly, I'm mostly running Nginx on Ubuntu and CentOS servers currently.

**Comment by noplanman** [comment]
@geerlingguy I honestly don't know any more. I've just checked with Debian 8, 9 and 10 and the latest Nginx version for all of them correctly has the default config in `sites-enabled`. So the initial problem of this issue seems fixed.

I still think being able configure the path is a plus though.
