### ISSUE TITLE
support for not defining a server name

### ISSUE THREAD

**Issue by JDeuce** [geerlingguy/ansible-role-nginx#132]
The vhost template has support to not set a server_name and then not have any section for it get written to the config:
   https://github.com/geerlingguy/ansible-role-nginx/blob/7aa2ea4779e4bd28c0f5a94489464e4da6f76049/templates/vhost.j2#L17-L19

However vhosts.yml
https://github.com/geerlingguy/ansible-role-nginx/blob/7aa2ea4779e4bd28c0f5a94489464e4da6f76049/tasks/vhosts.yml#L18 assumes that the server_name will be defined. This results in an error if you have not defined the server_name, even if you have defined a filename.

**Comment by longwave** [comment]
Please consider merging #145 as today is the fourth or fifth time I have run into this, where I don't need a `server_name` but am forced to define one.

**Comment by AndresPineros** [comment]
Please accept this

**Comment by JDeuce** [comment]
The fix in #145 was also marked as stale. Just wanted to update that I've tested this fix and it works for me. Reviewing the code shows it's simple, quick, and doesn't have any impact to backwards compatibility. If anyone was maintaining this repo should be quick to integrate that one and merge it in and close this.

**Comment by BillHoo** [comment]
+1, I have a lot proxy server running on the localhost, which means i don't need a `server_name` for these servers. this request seems reasonable
