### ISSUE TITLE
Allow for different LOG folders

### ISSUE THREAD

**Issue by Zauxst** [geerlingguy/ansible-role-nginx#134]
Hello I wish to organize better my log folders. But I have to build a task to manually create a folder different than default Debian location, "/var/log/nginx/" 

I wish to do "/var/log/nginx/server_name/acces+error.log"

**Comment by hadret** [comment]
It's roughly the same problem as mentioned here: https://github.com/geerlingguy/ansible-role-nginx/issues/143 It seems that having more flexibility in specifying nginx logs path would be beneficial for some role users.
