### ISSUE TITLE
Logfiles path on OpenBSD

### ISSUE THREAD

**Issue by elabaume** [geerlingguy/ansible-role-nginx#143]
Just a ridiculously small issue. According to [nginx(8)](https://man.openbsd.org/OpenBSD-5.6/nginx.8) in OpenBSD, the location for logfiles is /var/www/logs and not /var/log. Also note that /var/www is where nginx chroots to during startup on this OS.

**Comment by hadret** [comment]
The commit you provided with this bug report would not be enough. At the very least this would need fixing too: https://github.com/geerlingguy/ansible-role-nginx/blob/master/tasks/setup-OpenBSD.yml#L9 But that's not all, I'm afraid. Both `nginx_error_log` & `nginx_access_log` are providing more than just path -- you can set nginx to log directly into `syslog` using these, you can set different `log_formats` that you want to use, different log level you are interested in etc. etc. I think better way to approach this would be to introduce two new variables, let's say `nginx_logs_path` or separate ones for each (i.e. `nginx_error_log_path` & `nginx_access_log_path`). This would provide the possibility to specify something along these lines:

```
nginx_logs_path: /var/www # <- this being overridden for OpenBSD and being /var/log/nginx by default
nginx_error_log: "{{ nginx_logs_path }}/error.log warn"
nginx_access_log: "{{ nginx_logs_path }}/access.log main buffer=16k flush=2m"
```

The obvious problem with this approach is that it is a lot more involved and requires changes for pretty much every OS this role currently supports and not only OpenBSD.
