### ISSUE TITLE
Should the role manage all nginx configuration?

### ISSUE THREAD

**Issue by ibuchanan** [geerlingguy/ansible-role-nginx#146]
Just a question or discussion. There are a number of issues open with requests to make more or different configuration variables available to drive server and vhost configuration (for example: #59, #86, #137, #138, #141). I wonder if this is the wrong approach.

What this role does well is install nginx and configure it to run as a service. It is natural to want to configure nginx as well; however, I fear doing so has the logical conclusion of trying to model the entire nginx configuration language in YAML. While possible, I question the utility.

Instead, why not just rely on [overriding configuration templates](https://github.com/geerlingguy/ansible-role-nginx#overriding-configuration-templates)? The template can both fully express nginx configuration and Ansible configuration (using variables from your own playbook). If there is any consequence of favoring templates, it might be to remove simple configuration from the templates, forcing people to provide their own template files. Obviously, such a change would be a breaking change so maybe nothing need change at all.

**Comment by FinBoWa** [comment]
Id argue that the end product, ie working nginx configuration, is that you want and using an own template is just faster in some situations if you are proficient to create a functional nginx config file and most cost efficient way as the variables are timesaver when you want to quickly setup a nginx configuration, but might prevent you adding a configurations value to a specific point unless the role is modified 

So use what it provides would be my suggestion :) but there is no harm on submitting a pull request if you end up creating your on fork that adds the missing section to the generated templates without the need to use your own.
