### ISSUE TITLE
No Ubuntu-specific vars file

### ISSUE THREAD

**Issue by mixpix3ls** [geerlingguy/ansible-role-nginx#149]
Hi @geerlingguy ,

Great work and thank you for sharing it! I noticed that tasks/main.yml includes OS-specific variables and in the case of ansible_os_family being Ubuntu, I assumed there would be an Ubuntu.yml file in the vars directory. There is current no such file. Is that intended?

```
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
```

```
Files in ansible-role-nginx/vars/
Archlinux.yml
Debian.yml
FreeBSD.yml
OpenBSD.yml
RedHat.yml
```

Thanks!

**Comment by geerlingguy** [comment]
'Debian' is the os family for Ubuntu :)

**Comment by mixpix3ls** [comment]
Ah, my bad. Thanks for looking into it.
