### ISSUE TITLE
Nginx doesn't restart on Ubuntu 16.04

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/ansible-role-nginx#154]
Recently (perhaps after having `vagrant box update` to latest installed version: 1.1.8?) Nginx will only be running after a `vagrant provision` but not on subsequent `vagrant up` or `vagrant reload`. Otherwise it will be dead until I `vagrant ssh` and `sudo systemctl start nginx` after every time I `vagrant up` or `vagrant reload`.

The solution ([to a "known bug" since Feb 2017](https://stackoverflow.com/questions/42078674/nginx-service-failed-to-read-pid-from-file-run-nginx-pid-invalid-argument#42084804)) seems to be to wait for a bit on system (re)start as follows:  

    sudo su
    mkdir /etc/systemd/system/nginx.service.d
    printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" > /etc/systemd/system/nginx.service.d/override.conf
    systemctl daemon-reload
    systemctl restart nginx 

Has anyone else been experiencing this? (Perhaps it is now time to try the official nginx Ansible role as Jeff suggests? (Although I haven't seen yet how to adapt my `vagrant.config.yml` to do this yet.)

**Comment by iainhouston** [comment]
No, that's not the workaround. Nginx still fails to start automatically when I bring up the vm.

**Comment by ctaverne** [comment]
#151

**Comment by geerlingguy** [comment]
Closing in favor of https://github.com/geerlingguy/ansible-role-nginx/issues/154
