### ISSUE TITLE
BestPractice: firewalld

### ISSUE THREAD

**Issue by mr-deamon** [geerlingguy/ansible-role-nginx#166]
Hi
This is not a bug/issue. I am using this role to install nginx, which works perfectly! On my machines, firewalld is up and running, and nginx is available as soon i open the ports.
Where would you put this firewalld-task? Into the playbook, into another role, or - i don't think though - into a copy of this role?

Thanks for your ideas
chris

**Comment by replicajune** [comment]
in a dedicated [firewall](https://galaxy.ansible.com/geerlingguy/firewall) role ? :)

**Comment by geerlingguy** [comment]
@replicajune is correct; and for consistency I use iptables everywhere (since I manage a loooot of servers with many OSes, and iptables 'just works' everywhere, for the past decade+). But there are also some great firewalld roles on Galaxy if you want to stick with it's interface.
