### ISSUE TITLE
Is it possible to use latest version of NGINX for Ubuntu?

### ISSUE THREAD

**Issue by BR0kEN-** [geerlingguy/ansible-role-nginx#17]
What I need to specify in `nginx_default_release` variable to install the latest version of NGINX for this OS? I've tried "1.8.0" and "trusty". First variant was terminated with an error and second is installed the default stable version - "1.4.6".

**Comment by geerlingguy** [comment]
For Ubuntu, you can add a specific Nginx repository to your system in a task like:

    - name: Add nginx repository for the latest development release.
      apt_repository: repo='ppa:nginx/development'

Then set `nginx_default_release` to `nginx-development` in your playbook's variables, and you should get the latest development release.

**Comment by geerlingguy** [comment]
(or you may not even need to set the `nginx_default_release`... I think the PPA would override the system package in pin priorities, as long as you also update apt's caches after adding the repository.
