### ISSUE TITLE
tasks/vhosts.yml ignores root_group

### ISSUE THREAD

**Issue by src386** [geerlingguy/ansible-role-nginx#175]
https://github.com/geerlingguy/ansible-role-nginx/blob/master/tasks/vhosts.yml#L21

```group: root``` should be ```group: "{{ root_group }}"```

Until then the role is broken on FreeBSD: ```"msg": "chgrp failed: failed to look up group root"```

**Comment by geerlingguy** [comment]
@src386 is `root_group` a predefined/magic variable from Ansible? Or would that be a new variable to make it so a role user could change the value of `root_group` (with a default of `root`)?

**Comment by src386** [comment]
```root_group``` is a OS specific variable defined here:

https://github.com/geerlingguy/ansible-role-nginx/blob/master/vars/FreeBSD.yml#L2

**Comment by geerlingguy** [comment]
Ah, right you are! I think this is fixed in the commit above—will tag 2.6.2 with the fix once it passes tests.
