### ISSUE TITLE
The log format according defaults/main.yml breaks fail2ban log recognition

### ISSUE THREAD

**Issue by eHanseJoerg** [geerlingguy/ansible-role-nginx#179]
I have installed nginx using your role and I am using a VHOST for Odoo.
Except for the instruction where to put the access.log, no further log directives are defined.

When trying to integrate Fail2Ban to the system, Fail2Ban will not recognize the log format passed to this role according to the Fail2Ban logs. The message is this:

    Found a match ... but no valid date/time found* for ...

In Fail2Ban, I was able to correct the behaviour by additionally passing

    [Init]
    datepattern = %%d/%%b/%%Y:%%H:%%M:%%S

to my /etc/fail2ban/filter.d/odoo.conf.

I do not yet know if this is because of your role or because of fail2ban, but I am sure that this could be a side effect that is not intended by this role.  I am raising this issue for further investigation.

**Comment by hadret** [comment]
By default the role specifies the following `access_log` setup: https://github.com/geerlingguy/ansible-role-nginx/blob/master/defaults/main.yml#L24 Definition of the `main` can be found here: https://github.com/geerlingguy/ansible-role-nginx/blob/master/defaults/main.yml#L84 Default for nginx is `combined` and looks as follows:

```
log_format combined '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
```

So... yeah, there are a few differences. I'd start with defining `combined` for `access_log` and check whether this is working fine with the default setup of fail2ban.
