### ISSUE TITLE
Please add MacOS OSX Support

### ISSUE THREAD

**Issue by jleaders** [geerlingguy/ansible-role-nginx#180]
Please add support to install on MacOS systems.

Seems to me that one could use `when` statements to detect if you're on Darwin OS,
then and have a variable to pick between `brew install` or `port install` for nginx, 
and be able to install it on a MacOS system.

Currently if you try to install, you get an error looking for Darwin.yml. I presume that's due to the fact that MacOS is not a supported OS. I know Macs are not used for servers, but sometimes it's nice to spin up a dev server locally
```
localhost]: FAILED! => {
    "ansible_facts": {}, 
    "ansible_included_var_files": [], 
    "changed": false, 
    "message": "Could not find or access 'Darwin.yml'
}

```

**Comment by hadret** [comment]
That's quite involved change to introduce one more host and in this case makes not a lot of sense. I would not expect big use cases for macOS on server, you'd need to cover at least two or three ways of installing software (as there's no standard here, contrary to other supported UNIX and UNIX-like OSes) etc. And if you are not using MacPorts nor Homebrew then what? Compile from source?

If one need to spin up dev server locally, simply use Docker, Vagrant or [Multipass](https://github.com/CanonicalLtd/multipass) for the task and be done with it.

**Comment by jleaders** [comment]
I just figured it'd be as simple as `brew install nginx` or `port install nginx` -- all the config files should still be in `/etc/nginx` because MacOS is Unixy, so I didn't figure there was much else to do. 

(I wouldn't support compilation from source)
