### ISSUE TITLE
restart Nginx error

### ISSUE THREAD

**Issue by kyusupov33** [geerlingguy/ansible-role-nginx#190]
Provision vagrant with 'generic/ubuntu1904' and after try to reload Nginx get an error - 
```bash
RUNNING HANDLER [geerlingguy.nginx : restart nginx] ****************************
fatal: [default]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by kyusupov33** [comment]
After I destroy vagrant machine and up it again, the problem is resolve

**Comment by lionslair** [comment]
I get the same thing on the initial run every time

**Comment by lenguyenthanh** [comment]
Hi I'm facing this issue now. Any one knows how to solve it?
I'm using ubuntu 20 LTS on Digitial Ocean.
