### ISSUE TITLE
Nginx installation using ansible

### ISSUE THREAD

**Issue by VenkateshSarivisetty** [geerlingguy/ansible-role-nginx#191]
TASK [geerlingguy.nginx : Ensure nginx is installed.] ****************************
fatal: [172.31.94.167]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.\nhttp://nginx.org/packages/centos/2/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found"}

**Comment by seankibler** [comment]
@VenkateshSarivisetty It looks like Ansible is detecting your CentOS distribution version to be CentOS 2, if that is correct Nginx does not have packaged distribution support for CentOS older than 6. 

http://nginx.org/en/linux_packages.html

**Comment by gimbo** [comment]
Thanks @seankibler, just what I needed to know. :-)

**Comment by Lusitaniae** [comment]
Same issue, role needs handling for Amazon Linux
```
cat /etc/*release*
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
cpe:2.3:o:amazon:amazon_linux:2
```

**Comment by Lusitaniae** [comment]
still valid

**Comment by skrosoft** [comment]
still valid

**Comment by seankibler** [comment]
I'll see if I can throw together a PR for this.
