### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by tirelibirefe** [geerlingguy/ansible-role-nginx#192]
is there any explanation in somewhere?

**Comment by thewasta** [comment]
About what?
The README.md file has all information

**Comment by geerlingguy** [comment]
Not only that, there are example playbooks in the `molecule` directory too.

Or I recommend reading through my [Ansible for DevOps](https://www.ansiblefordevops.com) book if you're interested in learning about Ansible usage and roles in general ;)
