### ISSUE TITLE
Extra modules are not loaded (nginx.conf template miss modules-enabled include)

### ISSUE THREAD

**Issue by ncharlot** [geerlingguy/ansible-role-nginx#200]
In default Debian package `nginx.conf` we have:

    include /etc/nginx/modules-enabled/*.conf;

_package source: https://sources.debian.org/src/nginx/1.18.0-4/debian/conf/nginx.conf/_

This instruction is missing in the template causing that no extra module is dynamically loaded.

**Comment by eengstrom** [comment]
Too bad this just got closed - I have the same issue.

**Comment by ncharlot** [comment]
@eengstrom Yep…

**Comment by ncharlot** [comment]
@eengstrom I use this workaround (for instance to load `libnginx-mod-http-headers-more-filter`):

    nginx_extra_conf_options: |
      # Fix NGiNX modules load https://github.com/geerlingguy/ansible-role-nginx/issues/200
      include /etc/nginx/modules-enabled/*;

**Comment by eengstrom** [comment]
@ncharlot - thanks - was just about to the same point.   Will take your workaround.

**Comment by eengstrom** [comment]
/reopen

@geerlingguy: this line is in the stock `nginx.conf` file:

```
include /etc/nginx/modules-enabled/*.conf;
```

Is there a reason you left it out?  
Also, if I were to submit a PR to fix this, would you take it?
