### ISSUE TITLE
error in vhosts.conf requires manual removal

### ISSUE THREAD

**Issue by robotops** [geerlingguy/ansible-role-nginx#22]
If an error is accidentally injected into the vhosts.conf file, fixing it in the playbook won't take effect until the vhosts file is explicitly removed from the target host.  I think this occurs because the nginx restart is attempted before the include of vhosts.yml. When there's an error in the vhosts file on the target host, the startup fails and the playbook halts before the new vhost.conf can be generated with the fix.

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes

- include: vhosts.yml

**Comment by geerlingguy** [comment]
This was fixed as part of #36 - sorry about not updating this issue sooner!
