### ISSUE TITLE
nginx_listen_ipv6 is undefined in the vhost.js template

### ISSUE THREAD

**Issue by peterbabic** [geerlingguy/ansible-role-nginx#220]
Hello,
copying the `templates/vhost.j2` template and referencin it manually via
```yaml
nginx-vhosts:
  - template: "{{ playbook_dir }}/templates/vhost.j2"
 ```
throws the `"msg": "AnsibleUndefinedVariable: 'nginx_listen_ipv6' is undefined"` error when the playbook is run.

The error is gone when adding `is defined` to the L5 and L19
https://github.com/geerlingguy/ansible-role-nginx/blob/1820e90b4cf7248f0914983beeb785bf15bb0571/templates/vhost.j2#L5
https://github.com/geerlingguy/ansible-role-nginx/blob/1820e90b4cf7248f0914983beeb785bf15bb0571/templates/vhost.j2#L19

resulting in 
```j2
{% if nginx_listen_ipv6 is defined %}
```
following the convention throughout rest of the the template (every if block has `if defined` statement).

**Comment by julien-langlois** [comment]
Hi,

Unless I'm mistaken, this variable was added during the merge request #125 dated April 14th. 

In my opinion it's a variable you must be missing since the if condition in its simplest form tests if the variable is defined, not empty and not false.

**Comment by peterbabic** [comment]
Hello @julien-langlois,
thank you for the response. Please excuse me, I am unsure right now how to approach this, as I have been solving many other things since this one and frankly I do not really remember what was going on exactly. I will eventually get back to this and report back.
