### ISSUE TITLE
Nginx package not available from scratch

### ISSUE THREAD

**Issue by scarlac** [geerlingguy/ansible-role-nginx#24]
The playbook does not run the equivalent to `apt-get update` which means a fresh install of Debian 8.1 will fail to locate nginx (tested for Linode's Debian 8.1 standard image).

The role should require an apt update before it is run.

**Comment by scarlac** [comment]
(Or it should be a documented requirement in the README that apt is up to date)

**Comment by geerlingguy** [comment]
I think I'll add an update task that updates the cache if it's older than one day old (86400s).

**Comment by scarlac** [comment]
Perfect, thanks! :)
