### ISSUE TITLE
Template inheritance no longer works?

### ISSUE THREAD

**Issue by balaji-dutt** [geerlingguy/ansible-role-nginx#249]
Hi,

I was trying to use the inheritance feature as documented in [this section of the README](https://github.com/geerlingguy/ansible-role-nginx?tab=readme-ov-file#example-configure-gzip-in-nginx-configuration), but kept hitting an `jinja2.exceptions.TemplateNotFound` error.

After quite a bit of searching, I came across [this ansible issue](https://github.com/ansible/ansible/issues/20442) which if my understanding is correct implies that extending templates from installed roles is no longer possible. Indeed [this comment](https://github.com/ansible/ansible/issues/20442#issuecomment-444452824) on the issue specifically mentions trying to use the `geerlingguy.nginx` role as well and hitting an issue. 

Sadly it appears that this feature broke very shortly after it was merged into the role - may I suggest removing it from the README? I have to confess I spent quite a bit of time trying to figure out how to get this work thinking the issue was on my end and I'd like it if somebody benefited from the time I wasted!

**Comment by nono-lqdn** [comment]
This is important
