### ISSUE TITLE
Best way to add extra parameters

### ISSUE THREAD

**Issue by sagikazarmark** [geerlingguy/ansible-role-nginx#25]
I am trying to add the following to the extra parameters config:

``` yml
error_log /var/log/nginx/symfony2.error.log;
access_log /var/log/nginx/symfony2.access.log;

# strip app.php/ prefix if it is present
rewrite ^/app\.php/?(.*)$ /$1 permanent;
rewrite ^/app_dev\.php/?(.*)$ /$1 permanent;

location / {
    index app_dev.php;
    try_files $uri @rewriteapp;
}

location @rewriteapp {
    rewrite ^(.*)$ /app_dev.php/$1 last;
}

# pass the PHP scripts to FastCGI server from upstream phpfcgi
location ~ ^/(app|app_dev|config)\.php(/|$) {
    fastcgi_pass phpfcgi;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param  HTTPS off;
}
```

But I get an error:

`Failed to template {% if [{'extra_parameters': PARAMETER_STRING_HERE, ...my other parameters...] %} True {% else %} False {% endif %}: template error while templating string: expected token ',', got 'string'`

Is there a better way of doing this? Ultimately, I think there is room for improvement here, at least `location` configs should be able to configured here.

**Comment by sagikazarmark** [comment]
Tried lookup as well: `{{ lookup('file', 'vhost_extra') }}`

No luck

**Comment by geerlingguy** [comment]
@sagikazarmark - Sorry about that; I've added a better example for how you can add extra parameters: https://github.com/geerlingguy/ansible-role-nginx#role-variables

**Comment by geerlingguy** [comment]
I would like to figure out a slightly better/easier way at some point, but there's always (for now) the option of managing your own vhosts file and setting `nginx_vhosts: []` so this role doesn't manage any vhosts.

**Comment by sagikazarmark** [comment]
I started to play with the other way around: manage everything by the role.

You can take a look at here: https://github.com/indigophp/ansible-nginx/blob/master/tasks/configure.yml
