### ISSUE TITLE
Use official Nginx PPA for Debian/Ubuntu

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-nginx#27]
It should be relatively simple to do this, and would allow people to use the stable or development releases of Nginx more easily (without having to configure the PPA themselves, as I suggested in #17 ).

It seems it may be as simple as adding a task like:

``` yaml
- name: Add repository for Nginx.
  apt_repository: repo='ppa:nginx/{{ nginx_ppa_version }}'
```

And `nginx_ppa_version` would be either `stable` or `development`.

More docs in the Nginx install page: http://wiki.nginx.org/Install

**Comment by CrazyLionHeart** [comment]
Official repo for nginx described in http://nginx.org/en/linux_packages.html
