### ISSUE TITLE
add nginx_server_names_hash_bucket_size param

### ISSUE THREAD

**Issue by TPETb** [geerlingguy/ansible-role-nginx#28]
My server name is ec2-52-10-27-203.us-west-2.compute.amazonaws.com and I'm getting this error:
```
nginx: [emerg] could not build the server_names_hash, you should increase server_names_hash_bucket_size: 64
```
unfortunately the role doesn't give a possibility to override this setting now.

Thanks

**Comment by collex100** [comment]
I'm getting this error:
TASK [geerlingguy.nginx : Ensure nginx is started and enabled to start at boot.] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "nginx: [emerg] could not build the types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 32\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"}

Thanks

**Comment by geerlingguy** [comment]
Fixed via the above commit.
