### ISSUE TITLE
Can't set some http properties like gzip

### ISSUE THREAD

**Issue by mikegleasonjr** [geerlingguy/ansible-role-nginx#31]
I would be great to provide a hash to set generic values instead of specific variables like `nginx_client_max_body_size`...

-or-

Provide a dictionary of files to put in `conf.d/ `

I need to configure compression :(

**Comment by opdavies** [comment]
@mikegleasonjr There's a `nginx_extra_http_options` variable within nginx.conf.j2 where you can add extra things.

For example:

````
nginx_extra_http_options: |
  gzip on;
  gzip_proxied any;
  gzip_types text/plain text/xml text/css application/x-javascript;
  gzip_vary on;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";
````

**Comment by geerlingguy** [comment]
Yep! This was just added recently, and I'm going to start using it in my playbooks as well (rather than override the config file entirely).

**Comment by mikegleasonjr** [comment]
forgot about his issue, not using this role anymore...
