### ISSUE TITLE
vhost evaluation fails when role is wrapped and nested variables are used

### ISSUE THREAD

**Issue by asagage** [geerlingguy/ansible-role-nginx#33]
I was trying to create an application role that uses this role as a dependency.  In my application role, I pass in certain variables to your role including a vhost with a variable.  

Example:
```
  - role: geerlingguy.nginx
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "_"
        root: "{{ PROJECT_APP_PATH }}/dist"
```
This causes the following error...

```
TASK: [geerlingguy.nginx | Add managed vhost config file (if any vhosts are configured).] *** 
fatal: [127.0.0.1] => Failed to template {% if [{'root': u'$/vagrant/dist', 'server_name': '_', 'listen': '80 default_server'}] %} True {% else %} False {% endif %}: template error while templating string: expected token ',', got 'string'

FATAL: all hosts have already failed -- aborting
```

I made a fix for this and will PR. Although I am not 100% sure why this behavior occurs when using the role as a dependency and not when using it directly.  The issue seems to be related to the Jinja2 variable expansion as when I remove the variable, it works fine.

**Comment by geerlingguy** [comment]
Fixed in PR #34
