### ISSUE TITLE
Use http/2 by default

### ISSUE THREAD

**Issue by kallevu** [geerlingguy/ansible-role-nginx#59]
Is there any plans to use http2 by default for OS's that have OpenSSL 1.0.2+ and nginx 1.9.5+ ? 

From comments of https://by-example.org/install-nginx-with-http2-support-on-ubuntu-14-04-lts/

> "Unless the OpenSSL 1.0.2 package is installed, there is no ALPN support, so you will only get HTTP/2 support on clients that still support NPN. Unfortunately, OpenSSL 1.0.2 is not included in Ubuntu 14.04 LTS."

**Comment by robbyoconnor** [comment]
You can enable this pretty easily in your listen directive...

**Comment by adrinux** [comment]
But be aware that certbot doesn't add it by default for listen 443...

**Comment by robbyoconnor** [comment]
You can add it. You don't have to let certbot do everything.
