### ISSUE TITLE
nginx_user should verify user exists?

### ISSUE THREAD

**Issue by wesgarrison** [geerlingguy/ansible-role-nginx#6]
Brand new to ansible, so maybe this is my ignorance.

That said, I ran this and expected it to check that if there was no user `nginx` (by default) that it would create one (or at least tell me).  

After rebooting my VM, nginx didn't start because there wasn't a valid user account.

If this isn't The Ansible Way, that's fine (and there's a story for your book!)

**Comment by geerlingguy** [comment]
If you're running on Ubuntu, for now (until #8 is incorporated/fixed), please set the variable `nginx_user` to `www-data` in your own playbook's variables.

**Comment by geerlingguy** [comment]
Please see commit above — this sets the default user correctly and allows override via `nginx_user` variable. Thanks for reporting this!
