### ISSUE TITLE
Add variable to configure vhosts filename

### ISSUE THREAD

**Issue by pedronofuentes** [geerlingguy/ansible-role-nginx#61]
It could be interesting to have a variable to configure vhosts filename.

This allows you to call the role multiple times and configure hosts in separated files. At this moment if you do this the last call overrides `vhosts.conf`.

I implemented it in my fork: https://github.com/pedronofuentes/ansible-role-nginx/tree/add-vhosts-filename-configuration . If you want I can create a PR.

**Comment by geerlingguy** [comment]
That would be great! Would make this role work a little better for that use case.

**Comment by geerlingguy** [comment]
Fixed via #62.
