### ISSUE TITLE
How to geerling.nginx + geerling.php

### ISSUE THREAD

**Issue by Greg-Boggs** [geerlingguy/ansible-role-nginx#75]
Hi Jeff,

Sorry to bother you, but I've put a fair amount of time into trying to get the two roles working together and I've been unsuccessful. Do you have an example configuration that will get the two roles working together?

I've come close a couple of times, but the best I was able to do was to get nginx to execute index.php and then fail to load /test.php

**Comment by geerlingguy** [comment]
A couple examples here:

  - [Drupal VM Nginx config](https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/templates/nginx-vhost.conf.j2)
  - [lemp example in Ansible Vagrant Examples repo](https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/lemp)

I have a few other examples too, but haven't had time to post them up to GitHub (they still need to be cleansed of proprietary info...).
