### ISSUE TITLE
Question: Can the baseurl for the nginx be placed in a variable

### ISSUE THREAD

**Issue by devansatpat** [geerlingguy/ansible-role-nginx#79]
In the role, the nginx is downloaded from the http://nginx.org/packages/. Is it possible to define a variable for “/nginx.org” so that we can reuse it or give our own base url for download.

**Comment by geerlingguy** [comment]
I think the easiest way to allow this to be configurable would be to make the entire repo `baseurl` to be configurable as a variable (https://github.com/geerlingguy/ansible-role-nginx/blob/3f11a46b50f5d0f89f6b696cc9b84ea912663116/templates/nginx.repo.j2). Something like a new `nginx_repo_baseurl` variable.

**Comment by devansatpat** [comment]
can this be incorporated here in github for all of us to use?
