### ISSUE TITLE
Allow for extra 'listen' directives to enable ipv4/ipv6 simultaneously 

### ISSUE THREAD

**Issue by jmooo** [geerlingguy/ansible-role-nginx#86]
My default http and https nginx configs contain:

```
  listen 80;
  listen [::]:80;
```
and 
```
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
```

But the role template currently only allows a single `listen` directive. You can of course sneak a 2nd one in with the `extra_parameters` option, but I assume we're going to be supporting ipv4/ipv6 simultaneously for many years to come

**Comment by robbyoconnor** [comment]
FYI -- I did this in #125

**Comment by Seegras** [comment]
You can actually specify all FOUR (as many listen-directives as you want) in the same server directive; which your patch doesn't seem to allow.

**Comment by robbyoconnor** [comment]
@Seegras sure -- except that's inflexible -- this allows for more flexibility. What if someone doesn't want to listen on HTTPS? What if they want to use a non-standard port?

**Comment by robbyoconnor** [comment]
@Seegras this is true -- but that's a shortcoming of the role itself.

**Comment by robbyoconnor** [comment]
@Seegras -- additionally -- I think there's more flexibility this way -- and if you don't like how a template is setup, create your own template...so there are ways to fix this...my patch wasn't meant to do be a radical refactor -- just fix the one issue I wanted fixed.
