### ISSUE TITLE
Add brotli support

### ISSUE THREAD

**Issue by bountyh** [geerlingguy/ansible-role-nginx#87]
https://github.com/google/ngx_brotli adding optional support for this would be useful.

**Comment by hadret** [comment]
Is Google even still working on this? Project seems abandoned, last commit dates back to 2016. Besides, this is a third-party module that requires to be build from source -- this role is not providing this as an option (it uses packages or ports depending on the OS) and that's all. I don't think this issue belongs here, what you need is a third-party, custom built nginx package with third-party modules built-in.
