### ISSUE TITLE
Repo url needs updating for CentOS / EL 7

### ISSUE THREAD

**Issue by u-phoria** [geerlingguy/ansible-role-nginx#9]
In files/nginx.repo, currently we have
```
baseurl=http://nginx.org/packages/centos/6/$basearch/
```
Changing 6 to 7 works for me, otherwise I get
```
msg: Error: Package: nginx-1.6.2-1.el6.ngx.x86_64 (nginx)
           Requires: libpcre.so.0()(64bit)
```
Looks like the version # in the url needs to be dynamic?

**Comment by geerlingguy** [comment]
True, good catch!

**Comment by u-phoria** [comment]
Thanks Jeff - works great w/ CentOS 7 now.

I know Amazon Linux isn't listed as supported, for anyone using this on an ami unfortunately {{ ansible_distribution_major_version }} in nginx.repo.j2 resolves to "NA" on the latest Amazon Linux AMIs, e.g.

```
http://nginx.org/packages/centos/NA/x86_64/repodata/repomd.xml
```

The latest AMI works fine when that value is set to 6.
